### PR TITLE
[RTM] Added null check on packageReleaseJniLibs

### PR DESCRIPTION
**Pull request by renaudcerrato**
Android gradle plugin 1.5.0 I got a `packageReleaseJniLibs` not found. I simply added a null check.

### CODE REVIEW

**Comment by renaudcerrato** [comment]
any update on that?

**Comment by DoDoENT** [comment]
I think this is not good fix, as it misses JNI libs from AAR. The one that works for me is to use `mergeReleaseJniLibFolders` instead of `packageReleaseJniLibs`

**Comment by renaudcerrato** [comment]
Ok. I'm not a gradle expert. I'll wait for your fix then.

**Comment by adwiv** [comment]
Thanks @DoDoENT and @renaudcerrato . I have updated the code that should work with gradle plugin 1.5.

**Pull request closed without merging**
