### PR TITLE
Fix Gradle 3.3 + compiled path that contains /builds/ path 

### PR DESCRIPTION
**Pull request by nicolasd**
This fix some errors:
- Fix Gradle updates compatibility
- When the compiled destination contains /builds/ directory that is not inside the compiled files, compiled aar missed some resources

### CODE REVIEW

**Comment by Mklueh** [comment]
Thank you, this works perfectly with the latest Gradle version! Sadly the originator is inactive since a while and won´t merge it...

**Comment by adwiv** [comment]
Hi Nicholas, Thanks for the pull request. I am not active in development so unfortunately can't test  it, but am going to merge it assuming it works going by the Marian's comment.

**Comment by uberbinge** [comment]
@nicolasd hi did you already migrate to new Android 3.0 gradle plugin? the latest version breaks again now :(

[reported issue](https://github.com/adwiv/android-fat-aar/issues/81)

**Comment by nicolasd** [comment]
@waah42 sorry did not test yet with the 3.0.
I will look this as soon as possible and keep you in touch

**Comment by uberbinge** [comment]
@nicolasd thanks, looking forward to it 👍

**Comment by sarvesh-bisht** [comment]
@waah42 , Hi, have you got any workaround? I am also facing same issue with 3.0.

**Comment by uberbinge** [comment]
@sarveshbisht1987 sadly no not yet 😞

**Comment by Sarubbaru** [comment]
+1

**Pull request merged**
